name: R Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: EnergyQuant tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.6.1'
          use-public-rspm: true

      - name: Restore renv dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Run automated tests
        run: Rscript tests/testthat.R